language: python

sudo: required

services:
  - docker

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

install:
  - pip install . pytest mock codecov behave pexpect==3.3
  - pip install -e .

script:
  - coverage run --source wharfee -m py.test
  - cd tests
  - behave

after_success:
  - codecov
