language: python

sudo: required

services:
  - docker

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  # show docker version
  - docker --version

install:
  - pip install -r requirements-dev.txt
  - pip install codecov
  - pip install -e .

script:
  - coverage run --source wharfee -m py.test
  - cd tests
  - behave --tags ~@slow

after_success:
  - codecov
